### ISSUE TITLE
Contributions of Feb 2017

### ISSUE THREAD

**Issue by iamVP7** [MozillaTN/mozillatn-events#3]
Please add your blog post of open source events where you participated / gave talks / organised in Feb 2017. 

Contributions done by you also as a single blog post.

Last date to submit : March 5th

**Comment by surentharan** [comment]
SNSCT contributions on Firefox 52 Beta 3 Testday : https://mozillatn.github.io/snsct/blog/result-of-firefox-52-beta-7-testday

**Comment by sriram23** [comment]
CoderDojo Coimbatore Feb Session : (https://mozillatn.github.io/KiTE/blog/CoderDojo)

**Comment by prasanthp96** [comment]
Git and Github session at SKCET ( https://mozillatn.github.io/skcetzilla/event/gitevent )
