### ISSUE TITLE
Contributions of March 2017

### ISSUE THREAD

**Issue by iamVP7** [MozillaTN/mozillatn-events#4]
Please add your blog post of open source events where you participated / gave talks / organised in March 2017.

Contributions done by you also as a single blog post.

Last date to submit : March 31st

**Comment by surentharan** [comment]
**Bug Verification Day-20170301 at SNSCT**
https://mozillatn.github.io/snsct/blog/Result-of-bug-verificaton-day-20170301

**Comment by surentharan** [comment]
**Womoz day celebration at SNSCT**
https://mozillatn.github.io/snsct/blog/womens-day-celebration

**Comment by surentharan** [comment]
**Firefox 53.0 Aurora Testday at SNSCT**
https://mozillatn.github.io/snsct/blog/Result-of-Firefox-53.0-Aurora-Testday

**Comment by surentharan** [comment]
**Bug Verification Day-20170308 at SNSCT**
https://mozillatn.github.io/snsct/blog/Result-of-Bug-Verification-Day-20170308

**Comment by surentharan** [comment]
**Bug Verification day-20170315 at SNSCT**
https://mozillatn.github.io/snsct/blog/Result-of-Bug-Verification-Day-20170315

**Comment by surentharan** [comment]
**Firefox 53 Beta 3 Testday at SNSCT**
https://mozillatn.github.io/snsct/blog/Result-of-Firefox-53-Beta-3-Testday

**Comment by Balaji2198** [comment]
participation in **open source hack**:
https://balajiwebblog.wordpress.com/2017/03/19/mozilla-open-source-hack/

**Comment by surentharan** [comment]
**Bug Triage Day - 20170327 at SNSCT**
https://mozillatn.github.io/snsct/blog/Result-of-Bug-Triage-Day-20170327

**Comment by dvigneshwer** [comment]
## MozIN Rust Events

**Event Links:**
* [Building AI models using Rust - Talk at Fossmeet17](https://reps.mozilla.org/e/rust-intro-fossmeet-2017/)
* [Building AI models using Rust - Workshop at A3K Rajagiri College ](https://reps.mozilla.org/e/rust-hack-ernakulam/)
* [Introduction to Rust - Madurai](https://reps.mozilla.org/e/rust-hack-madurai/)

**Comment by Balaji2198** [comment]
**Bug Triage Day - 20170327 at SRMOZILLA**
https://mozillatn.github.io/srmozilla/blog/Result-of-Bug-Triage-Day-20170327

**Comment by baranitharan2020** [comment]
**MozCafe Tanjore on March 12th 2017**
http://kingsmozilla.blogspot.in/2017/03/mozcafetanjore12032017.html?m=1

**Comment by surentharan** [comment]
**Webcompat Hackathon on march 30th 2017 at SNSCT**
https://mozillatn.github.io/snsct/blog/Webcompat-Hackathon

**Comment by surentharan** [comment]
**Firefox 53 Beta 8 Testday at SNSCT**
https://mozillatn.github.io/snsct/blog/Result-of-Firefox-53-Beta-8-Testday

**Comment by surentharan** [comment]
**Bug Verification Day - 20170329 at SNSCT**
https://mozillatn.github.io/snsct/blog/Result-of-Bug-Verification-Day-20170329

**Comment by surentharan** [comment]
**Bug Verification Day - 20170322 at SNSCT**
https://mozillatn.github.io/snsct/blog/Result-of-Bug-Verification-Day-20170322

**Comment by iamVP7** [comment]
Thanks for everyone who submitted.
